### ISSUE TITLE
Unable to deploy in Docker swarm

### ISSUE THREAD

**Issue by DreiPixel** [origamiofficial/docker-pihole-unbound#22]
This is a: **Run Issue**  

## Details

I tried to run this Docker image on my Docker Swarm and it fails with this error message in the Logs:

```
Stopping lighttpd
s6-rc: info: service lighttpd successfully stopped
s6-rc: info: service pihole-FTL: stopping
Stopping pihole-FTL

  [✗] Unable to fill table adlist in database /etc/pihole/gravity.db

s6-rc: info: service pihole-FTL successfully stopped
s6-rc: info: service _startup: stopping
Terminated
s6-rc: info: service _startup successfully stopped
s6-rc: info: service _uid-gid-changer: stopping
s6-rc: info: service _uid-gid-changer successfully stopped
s6-rc: info: service cron: stopping
  [i] Cleaning up stray matter...Stopping cron
s6-rc: info: service cron successfully stopped
s6-rc: info: service legacy-cont-init: stopping
  [✓] Cleaning up stray matter
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

the Normal Pihole Docker image Runs fine. 
What is also noticed that the pihole folder i use gets the permission changed from the usual default i give it to 999:lxd which im pretty sure the normal image doesnt.
also had it stuck hard on the unbound.sh once and the container wouldn't get killed.

## Related Issues
- [ ] I have searched this repository/Pi-hole official repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu Server 22.04**
  * Hardware: Turing RK1 
  * Kernel Architecture: aarch64 
  * Docker Install Info and version: 
    - Software source: docker-ce 
    - Supplimentary Software: portainer
  * Hardware architecture: aarch64 
  * Docker Image Tag: latest 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: '3.8'

services:
  pihole:
    image: rlabinc/pihole-unbound:latest

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host

    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${WEBPASSWORD}

    volumes:
      - type: bind
        source: /mnt/docker-storage-ssd/pihole/pihole
        target: /etc/pihole
      - type: bind
        source: /mnt/docker-storage-ssd/pihole/dnsmasq.d
        target: /etc/dnsmasq.d

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
```

3. any additional info to help reproduce
the cluster is running with 4 nodes and all nodes have access to the same files via glusterfs.
and i know that this might be hard to debug. but since im only running this on one node this should be the same as running it on a normal system

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X] I have tried running official Pi-hole docker image to check if it works there

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by origamiofficial** [comment]
Is this a fresh installation?

Send me the unbound log file located at `/opt/unbound/etc/unbound/unbound.log` inside the container.

Also try this solution: https://github.com/origamiofficial/docker-pihole-unbound/issues/21#issuecomment-1913541536

**Comment by DreiPixel** [comment]
the log is completely empty.
also tried the solution you suggested.
when i try to restart it fails now at this "Unable to create new database /etc/pihole/gravity.db_temp"

**Comment by origamiofficial** [comment]
Tried fresh install without the volumes?

**Comment by DreiPixel** [comment]
it stopped compaining about unable to create new database but still wont start.
Current docker compose file looks like this.
```
version: '3.8'

services:
  pihole:
    image: rlabinc/pihole-unbound:latest

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "192.168.3.203:53:53/tcp" 
      - "192.168.3.203:53:53/udp"
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${WEBPASSWORD}

      # This below is just Docker Swarm stuff
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.pihole == true ]
      restart_policy:
        condition: on-failure
        max_attempts: 3
```
