### ISSUE TITLE
SERVFAIL exceeded the maximum number of sends

### ISSUE THREAD

**Issue by Dillton** [origamiofficial/docker-pihole-unbound#34]
Hello, I am getting SERVFAIL exceeded the maximum number of sends for almost every web when DNS resolver is set to unbound.
Mostly it just need one page reload and it works but there are also pages when it takes several minutes of refreshing.
When I switch from unbound to other DNS resolver everything is working absolutely fine.
Below are examples from unbound log.
![Image](https://github.com/user-attachments/assets/7e284c56-cb7c-4f26-98bc-47e3e869382c)

I tried several things looking for closed/open issues like checking the time and date, playing with DNSSEC, change some unbound settings, also tried to disable firewall on my router device but nothing solved the problem.
Currently I have clean redeployed container with DNS resolver set to OpenDNS and everything works.

Strange is that when the container is fresh or restarted the resolution with unbound works for a few approx 20 pages and then starts hanging.

My setup is as follows:
Router Mikrotik RB5009 serving DHCP pool 10.0.0.0/24 which has DNS set to PiHole-main on 10.0.0.51 and PiHole-backup on 10.0.0.5. Router itself has DNS set to OpenDNS IPs. There are no VLANs or other super advanced configurations which could cause routing problems etc... as this is home setup so no reason to do it too much complicated.
PiHole-Main is running in Docker LXC in ProxmoxVE more info in Env. section below. PiHole-backup is running on SynologyNAS.
**Both environments have the same behaviour.**

I have opened also issue on unbound github as I am not sure if the problem is unbound or this container or elsewhere.

This is a: **Bug**  

## Details with Docker log

In docker log there is nothing but info about container starting.

## How to reproduce the issue 

1. Environment data
  * Operating System: **Docker LXC from https://tteck.github.io/Proxmox/ in ProxmoxVE and Synology DSM** 
  * Hardware: Intel NUC 13 Pro i7 and Synology DS218+ 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: For NUC it's Standalone 27.5.0 and NAS is 24.0.2 
    - Supplimentary Software: Portainer Agent 1.6.1 
  * Hardware architecture: x86 
  * Docker Image Tag: latest 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
NUC:
```
services:
  pihole:
    container_name: pihole-unbound
    image: rlabinc/pihole-unbound:latest
    hostname: pi-hole-main
    ports:
      - 10.0.0.51:53:53/tcp
      - 10.0.0.51:53:53/udp
      - 20080:80/tcp
      - 5335:5335/tcp # Enable unbound access on local server
    environment:
      FTLCONF_LOCAL_IPV4: 10.0.0.51
      FTLCONF_MAXDBDAYS: 30
      FTLCONF_RATE_LIMIT: 3000/60
      TZ: Europe/Prague
      WEBPASSWORD: xyz
      DNSSEC: true
      DNS_BOGUS_PRIV: true
      DNS_FQDN_REQUIRED: true
      DNSMASQ_LISTENING: single
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSMASQ_USER: root
      #SKIPGRAVITYONBOOT: 1
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - /var/lib/docker/volumes/pihole-unbound/pihole:/etc/pihole
      - /var/lib/docker/volumes/pihole-unbound/dnsmasq.d:/etc/dnsmasq.d
      - /var/lib/docker/volumes/pihole-unbound/unbound:/opt/unbound/etc/unbound
    restart: always
```
NAS:
```
services:
  pihole:
    container_name: pihole-unbound-backup
    image: rlabinc/pihole-unbound:latest
    hostname: pi-hole-backup
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 20080:80/tcp
      - 5335:5335/tcp # Enable unbound access on local server
    environment:
      FTLCONF_LOCAL_IPV4: 10.0.0.5
      FTLCONF_MAXDBDAYS: 30
      FTLCONF_RATE_LIMIT: 3000/60
      TZ: Europe/Prague
      WEBPASSWORD: xyz
      DNSSEC: true
      DNS_BOGUS_PRIV: true
      DNS_FQDN_REQUIRED: true
      DNSMASQ_LISTENING: single
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSMASQ_USER: root
      #SKIPGRAVITYONBOOT: 1
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - /volume1/docker/pihole-unbound/pihole:/etc/pihole
      - /volume1/docker/pihole-unbound/dnsmasq.d:/etc/dnsmasq.d
      - /volume1/docker/pihole-unbound/unbound:/opt/unbound/etc/unbound
    restart: always
```
## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have tried running official Pi-hole docker image to check if it works there
